[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "basyx-security"
version = "0.1.0"
description = "Security implementation layer for Eclipse BaSyx Python SDK"
readme = "README.md"
authors = [
    { name = "Hadi Jannat", email = "h.jannat@example.com" }
]
license = { text = "Apache-2.0" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Security",
]
dependencies = [
    "basyx-python-sdk>=0.1.0",
    "cryptography>=3.4.7",
    "pyjwt>=2.1.0",
    "python-dateutil>=2.8.2",
    "requests>=2.26.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.2.5",
    "pytest-cov>=2.12.0",
    "black>=21.5b2",
    "mypy>=0.910",
    "flake8>=3.9.2",
]

[project.urls]
Homepage = "https://github.com/hadijannat/basyx-security-layer"
Repository = "https://github.com/hadijannat/basyx-security-layer.git"
Documentation = "https://github.com/hadijannat/basyx-security-layer/docs"

[tool.setuptools]
packages = ["basyx_security"] 